// src/app/admin/circuit-mindmap/page.tsx
'use client';

import React, { useState, useEffect, useMemo } from 'react';
import { useRouter } from 'next/navigation';
import Link from 'next/link';
import { 
  GitMerge, 
  Database, 
  Cpu, 
  TrendingUp,
  Award,
  List,
  Grid,
  Folder,
  FolderOpen,
  ChevronDown,
  ChevronRight,
  Zap,
  ArrowRight,
  ArrowLeft,
  FileText
} from 'lucide-react';
import { MindMapCircuitSelector } from '@/components/mindmap/MindMapCircuitSelector';
import { CircuitBindingStatus } from '@/ai/mindmap/mindmap-circuit-binder';

export default function MindMapAdminPage() {
  const router = useRouter();
  const [circuits, setCircuits] = useState<CircuitBindingStatus[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  
  // 🚀 Innovative Feature: Dual View Modes (Grid cards & Hierarchical tree view)
  const [viewMode, setViewMode] = useState<'grid' | 'hierarchy'>('grid');
  const [expandedZones, setExpandedZones] = useState<Record<string, boolean>>({});

  const fetchStatus = async () => {
    setIsLoading(true);
    try {
      const res = await fetch('/api/circuit-mindmap/list');
      if (!res.ok) throw new Error('Échec du chargement des statuts de circuits');
      const data = await res.json();
      if (data.success) {
        setCircuits(data.circuits);
        
        // Auto-expand first zone by default in hierarchy view
        const firstZone = data.circuits[0]?.zoneId;
        if (firstZone) {
          setExpandedZones(prev => ({ ...prev, [firstZone]: true }));
        }
      }
    } catch (err) {
      setError(err instanceof Error ? err.message : String(err));
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    fetchStatus();
  }, []);

  const handleSelectCircuit = (circuitId: string) => {
    router.push(`/admin/circuit-mindmap/editor?circuitId=${circuitId}`);
  };

  const handleAutoGenerate = async (circuitId: string) => {
    setIsLoading(true);
    try {
      const res = await fetch(`/api/circuit-mindmap/upload`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          circuitId,
          content: '',
          format: 'json',
          metadata: { autoGenerated: true }
        })
      });

      const data = await res.json();
      if (!res.ok || !data.success) {
        throw new Error(data.error || 'Erreur lors de la génération automatique');
      }

      await fetchStatus();
    } catch (err) {
      alert(err instanceof Error ? err.message : String(err));
    } finally {
      setIsLoading(false);
    }
  };

  // Grouping circuits by zoneId for Hierarchical Tree view
  const groupedZones = useMemo(() => {
    const map: Record<string, CircuitBindingStatus[]> = {};
    circuits.forEach(c => {
      const z = c.zoneId || 'Sans Zone';
      if (!map[z]) map[z] = [];
      map[z].push(c);
    });
    return map;
  }, [circuits]);

  const toggleZone = (zoneId: string) => {
    setExpandedZones(prev => ({
      ...prev,
      [zoneId]: !prev[zoneId]
    }));
  };

  // Calculate statistics
  const totalCircuits = circuits.length;
  const circuitsWithMindmap = circuits.filter(c => c.hasMindmap).length;
  const missingCount = totalCircuits - circuitsWithMindmap;
  const totalParameters = circuits.reduce((acc, c) => acc + c.nodesCount, 0);
  const coveragePercent = totalCircuits > 0 ? Math.round((circuitsWithMindmap / totalCircuits) * 100) : 0;

  return (
    <div className="min-h-screen bg-slate-950 text-slate-100 p-8 space-y-8">
      {/* 🚀 Top Heading Banner */}
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4 bg-slate-900/40 p-6 rounded-3xl border border-white/10 backdrop-blur-md shadow-xl">
        <div className="flex items-center gap-4">
          {/* ← Bouton Retour Arrière */}
          <Link
            href="/admin"
            className="p-2.5 bg-white/5 hover:bg-white/10 border border-white/10 rounded-xl text-slate-400 hover:text-white transition-all active:scale-95 shrink-0"
            title="Retour à l'Administration"
          >
            <ArrowLeft className="w-5 h-5" />
          </Link>

          <div className="p-3.5 bg-orange-600/10 border border-orange-500/20 text-orange-400 rounded-2xl shadow-lg shadow-orange-500/5 animate-pulse">
            <GitMerge className="w-7 h-7" />
          </div>
          <div className="text-left">
            <h1 className="text-2xl font-black text-white uppercase tracking-wider">Mind Map Circuit</h1>
            <p className="text-xs text-slate-400 mt-1">
              Topologie de compréhension sémantique RAG & cartographie des interdépendances industrielles.
            </p>
          </div>
        </div>
      </div>

      {/* 📊 Premium Statistics Widgets */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
        {/* Coverage Widget */}
        <div className="bg-slate-900/40 border border-white/10 p-5 rounded-2xl flex items-center justify-between shadow-lg">
          <div className="space-y-1 text-left">
            <span className="text-[10px] text-slate-400 font-bold uppercase tracking-widest block">Couverture RAG</span>
            <span className="text-3xl font-black text-white">{coveragePercent}%</span>
            <span className="text-[10px] text-emerald-400 font-semibold block">Indexation Active</span>
          </div>
          <div className="w-14 h-14 rounded-full border-4 border-orange-500 border-t-transparent flex items-center justify-center font-bold text-xs">
            {circuitsWithMindmap}/{totalCircuits}
          </div>
        </div>

        {/* Total Nodes Widget */}
        <div className="bg-slate-900/40 border border-white/10 p-5 rounded-2xl flex items-center justify-between shadow-lg">
          <div className="space-y-1 text-left">
            <span className="text-[10px] text-slate-400 font-bold uppercase tracking-widest block">Nœuds Cartographiés</span>
            <span className="text-3xl font-black text-sky-400">{totalParameters}</span>
            <span className="text-[10px] text-slate-500 block">Paramètres & formules</span>
          </div>
          <div className="p-3 bg-sky-500/10 border border-sky-500/20 text-sky-400 rounded-xl">
            <Database className="w-6 h-6" />
          </div>
        </div>

        {/* Missing Maps Widget */}
        <div className="bg-slate-900/40 border border-white/10 p-5 rounded-2xl flex items-center justify-between shadow-lg">
          <div className="space-y-1 text-left">
            <span className="text-[10px] text-slate-400 font-bold uppercase tracking-widest block">Schémas Requis</span>
            <span className="text-3xl font-black text-orange-400">{missingCount}</span>
            <span className="text-[10px] text-slate-500 block">Circuits orphelins</span>
          </div>
          <div className="p-3 bg-orange-500/10 border border-orange-500/20 text-orange-400 rounded-xl">
            <Cpu className="w-6 h-6" />
          </div>
        </div>

        {/* RAG Efficiency Badge */}
        <div className="bg-gradient-to-br from-orange-600/20 to-orange-900/10 border border-orange-500/20 p-5 rounded-2xl flex items-center justify-between shadow-lg">
          <div className="space-y-1 text-left">
            <span className="text-[10px] text-orange-400 font-bold uppercase tracking-widest block">Statut RAG</span>
            <span className="text-xl font-bold text-white flex items-center gap-1.5 mt-1">
              <Award className="w-5 h-5 text-orange-400" />
              <span>Optimisé</span>
            </span>
            <span className="text-[10px] text-orange-300/60 block">Métadonnées topologiques actives</span>
          </div>
        </div>
      </div>

      {/* 🔌 Main Circuit List Section */}
      <div className="space-y-6">
        <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4 border-b border-white/10 pb-4">
          <div className="flex items-center gap-2">
            <TrendingUp className="w-4 h-4 text-orange-500" />
            <h2 className="text-xs font-black uppercase tracking-wider text-slate-400">Cartographie par Circuit</h2>
          </div>

          {/* 🚀 View Mode Switcher */}
          <div className="bg-white/5 border border-white/10 rounded-xl p-1 flex items-center gap-1">
            <button
              onClick={() => setViewMode('grid')}
              className={`flex items-center gap-1.5 px-3.5 py-1.5 rounded-lg text-xs font-bold transition-all ${
                viewMode === 'grid' 
                  ? 'bg-orange-600 text-white shadow-md' 
                  : 'text-slate-400 hover:text-white'
              }`}
            >
              <Grid className="w-3.5 h-3.5" />
              <span>Grille</span>
            </button>
            <button
              onClick={() => setViewMode('hierarchy')}
              className={`flex items-center gap-1.5 px-3.5 py-1.5 rounded-lg text-xs font-bold transition-all ${
                viewMode === 'hierarchy' 
                  ? 'bg-orange-600 text-white shadow-md' 
                  : 'text-slate-400 hover:text-white'
              }`}
            >
              <List className="w-3.5 h-3.5" />
              <span>Vue Hiérarchique</span>
            </button>
          </div>
        </div>
        
        {isLoading && circuits.length === 0 ? (
          <div className="flex flex-col items-center justify-center py-20 gap-2">
            <div className="w-8 h-8 rounded-full border-2 border-orange-500 border-t-transparent animate-spin" />
            <span className="text-[10px] uppercase font-bold tracking-widest text-slate-500">Chargement des données...</span>
          </div>
        ) : error ? (
          <div className="text-center py-20 text-red-400 text-sm">
            {error}
          </div>
        ) : viewMode === 'grid' ? (
          <MindMapCircuitSelector
            circuits={circuits}
            onSelect={handleSelectCircuit}
            onAutoGenerate={handleAutoGenerate}
            isLoading={isLoading}
          />
        ) : (
          /* 🌳 Breathtaking Expandable Hierarchical Explorer Tree */
          <div className="space-y-4 max-w-4xl mx-auto">
            {Object.keys(groupedZones).map(zoneId => {
              const zoneCircuits = groupedZones[zoneId];
              const isExpanded = !!expandedZones[zoneId];
              const activeCount = zoneCircuits.filter(c => c.hasMindmap).length;

              return (
                <div key={zoneId} className="bg-slate-900/30 border border-white/10 rounded-2xl overflow-hidden backdrop-blur-md">
                  {/* Zone Header Item */}
                  <button
                    onClick={() => toggleZone(zoneId)}
                    className="w-full flex items-center justify-between p-4.5 bg-slate-900/60 hover:bg-slate-900 transition-colors border-b border-white/5"
                  >
                    <div className="flex items-center gap-3">
                      <div className="text-slate-400">
                        {isExpanded ? <FolderOpen className="w-5 h-5 text-orange-400" /> : <Folder className="w-5 h-5 text-amber-500" />}
                      </div>
                      <div className="text-left">
                        <span className="text-xs font-black uppercase tracking-wider text-white">Zone : {zoneId}</span>
                        <span className="text-[10px] text-slate-400 font-medium block mt-0.5">
                          {zoneCircuits.length} circuit{zoneCircuits.length > 1 ? 's' : ''} • {activeCount} actif{activeCount > 1 ? 's' : ''}
                        </span>
                      </div>
                    </div>
                    <div className="text-slate-400">
                      {isExpanded ? <ChevronDown className="w-4 h-4" /> : <ChevronRight className="w-4 h-4" />}
                    </div>
                  </button>

                  {/* Nested Circuits List */}
                  {isExpanded && (
                    <div className="divide-y divide-white/5 p-2 bg-slate-950/20">
                      {zoneCircuits.map(circuit => (
                        <div
                          key={circuit.id}
                          className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 p-4 hover:bg-white/5 transition rounded-xl"
                        >
                          <div className="flex items-start gap-3">
                            <div className="p-2 rounded-lg bg-white/5 border border-white/10 mt-0.5">
                              <FileText className="w-4 h-4 text-slate-400" />
                            </div>
                            <div className="text-left">
                              <div className="flex items-center gap-2 flex-wrap">
                                <span className="text-xs font-bold text-white">{circuit.name}</span>
                                <span className="text-[9px] font-mono text-slate-400">({circuit.id})</span>
                                {circuit.hasMindmap ? (
                                  <span className="bg-emerald-500/10 border border-emerald-500/30 text-emerald-400 text-[8px] font-bold uppercase px-1.5 py-0.5 rounded flex items-center gap-1">
                                    <span className="w-1 h-1 rounded-full bg-emerald-400 animate-pulse" />
                                    🧠 Actif
                                  </span>
                                ) : (
                                  <span className="bg-orange-500/10 border border-orange-500/30 text-orange-400 text-[8px] font-bold uppercase px-1.5 py-0.5 rounded">
                                    ⚠️ Requis
                                  </span>
                                )}
                              </div>
                              {circuit.description && (
                                <p className="text-[10px] text-slate-400 mt-1 max-w-xl leading-relaxed">{circuit.description}</p>
                              )}
                              <div className="flex items-center gap-3 mt-2 text-[9px] text-slate-500 font-mono">
                                <span>Paramètres cartographiés : <strong className="text-slate-300 font-semibold">{circuit.nodesCount}</strong></span>
                                {circuit.updatedAt && (
                                  <>
                                    <span>•</span>
                                    <span>Mise à jour : {new Date(circuit.updatedAt).toLocaleDateString()}</span>
                                  </>
                                )}
                              </div>
                            </div>
                          </div>

                          <div className="flex items-center gap-2 shrink-0 self-end sm:self-center">
                            {!circuit.hasMindmap && (
                              <button
                                onClick={() => handleAutoGenerate(circuit.id)}
                                className="flex items-center gap-1 px-3 py-1.5 bg-orange-600 hover:bg-orange-500 text-white rounded-lg text-[10px] font-bold uppercase tracking-wider shadow-lg active:scale-95 transition-all"
                              >
                                <Zap className="w-3 h-3" />
                                <span>Auto-Générer</span>
                              </button>
                            )}
                            <button
                              onClick={() => handleSelectCircuit(circuit.id)}
                              className="flex items-center gap-1 px-3 py-1.5 bg-white/5 hover:bg-white/10 border border-white/10 text-white rounded-lg text-[10px] font-bold uppercase tracking-wider active:scale-95 transition-all"
                            >
                              <span>Ouvrir l'Atelier</span>
                              <ArrowRight className="w-3 h-3 text-slate-400" />
                            </button>
                          </div>
                        </div>
                      ))}
                    </div>
                  )}
                </div>
              );
            })}
          </div>
        )}
      </div>
    </div>
  );
}
